# Generated by Django 3.2.11 on 2022-05-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(upload_to='media/course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
            ],
        ),
    ]
