# Generated by Django 3.2.11 on 2022-05-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_course_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_description', models.TextField()),
                ('notice_title', models.CharField(max_length=100)),
                ('notice_image', models.ImageField(upload_to='media/notice')),
                ('notice_file', models.FileField(upload_to='media/notice')),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
