# Generated by Django 3.2.11 on 2022-05-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20220522_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='course_name',
            new_name='course',
        ),
    ]
