# Generated by Django 3.2.11 on 2022-05-22 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_rename_course_name_notice_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_description', models.TextField()),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_image', models.ImageField(upload_to='media/assignment')),
                ('assignment_file', models.FileField(upload_to='media/assignment')),
                ('assignment_submission_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
