# Generated by Django 3.2.11 on 2022-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_student_studentcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_submission_date',
            field=models.CharField(max_length=100),
        ),
    ]
