# Generated by Django 3.2.11 on 2022-05-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
    ]
