# Generated by Django 3.2.11 on 2022-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_remove_submission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(null=True, upload_to='media/submission'),
        ),
    ]
