# Generated by Django 3.2.11 on 2022-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_submission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submisssion_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submisssion_thoughts',
            field=models.TextField(null=True),
        ),
    ]
