# Generated by Django 3.2.11 on 2022-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20220523_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submisssion_marks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
